name: "Check Build"
description: "Action to Check the Build build command was run and optionally comment on the PR."
author: "Shane"
branding:
  icon: "play-circle"
  color: "green"

inputs:
  install:
    description: "Install Command to Run"
    default: "npm ci"
  build:
    description: "Build Command to Run"
    default: "npm run build"
  check:
    description: "Check Command to Run"
    default: "git diff --quiet dist"
  path:
    description: "Path to Verify First"
    default: ""
  comment:
    description: "Add Comment to PR"
    default: "true"
  message:
    description: "Message for Comment"
    default: "Run: `npm run build`"
  mention:
    description: "Mention Actor with @"
    default: "true"
  summary:
    description: "Add Workflow Job Summary"
    default: "true"
  token:
    description: "GitHub Token"
    default: ${{ github.token }}

outputs:
  id:
    description: "Comment ID"
  error:
    description: "Error Message"

runs:
  using: "node24"
  main: "dist/index.js"
