name: "Test"

on:
  workflow_dispatch:
  schedule:
    - cron: "18 18 * * 1,3,5"
  push:
    branches: ["master"]
    paths:
      - "dist/**"
      - "src/**"
      - "package*.json"
      - "requirements*.txt"
      - ".github/workflows/test.yaml"
      - "action.yml"
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      pull-requests: write

    steps:
      - name: "Checkout"
        uses: actions/checkout@v5

      - name: "Debug event.json"
        continue-on-error: true
        run: |
          cat "${GITHUB_EVENT_PATH}"

      - name: "Install"
        run: |
          if [ ! -d "node_modules" ];then
            echo "Running: npm ci"
            npm ci
          fi

      - name: "Test Local Action"
        id: test
        uses: ./
        with:
          path: "dist"

      - name: "Verify Outputs"
        env:
          ERROR: ${{ steps.test.outputs.error }}
        run: |
          echo "id: ${{ steps.test.outputs.id }}"
          #if [ -z '${{ steps.test.outputs.id }}' ];then
          #  echo "No Output: id"
          #  exit 1
          #fi
          echo "error: ${ERROR}"
          #if [ -z "${ERROR}" ];then
          #  echo "No Output: error"
          #  exit 1
          #fi

      - name: "Schedule Failure Notification"
        if: ${{ failure() && github.event_name == 'schedule' }}
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
